#!env ruby
#
# Pillarworld main executable
#

# Change working directory to the PW folder
Dir.chdir(__dir__);
$LOAD_PATH.push('lib');

require 'console';
require('./main.rb');

$console.log('Pillarworld main executable, yay');

$menu.show(:simple);

sleep;
