#!env ruby

# Change working directory to the PW folder
Dir.chdir(__dir__);

require('./console.rb');
require('./main.rb');

$console.log('Pillarworld main executable, yay');

$menu.show(:simple);

sleep;
